# Generated by Django 4.2.4 on 2023-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='otp_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'poll')},
        ),
    ]
