# Generated by Django 4.2.4 on 2023-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ManyToManyField(related_name='choices', to='polls.poll'),
        ),
    ]
